/* =========================
   BRANCH ANALYSIS
========================= */

#Total REvenue Generated
SELECT SUM(Amount) AS TotalRevenue 
FROM branchrevenue;

#Revenue Generated BY Branch
SELECT * FROM branchrevene;
SELECT branch_name,
		SUM(amount) AS total 
FROM branchrevenue 
GROUP by branch_name 
ORDER BY total DESC;

#Revenue Generated by Income Class
SELECT income_class,
		SUM(amount) as Total 
FROM branchrevenue 
GROUP BY income_class 
Order by total DESC;

#executive Generating more revenue
SELECT accountexeId,
		exename,sum(amount) AS total 
FROM branchrevenue 
GROUP BY accountexeid,exename 
Order by total DESC LIMIT 10;

#Revenue Type Revenue
SELECT revenue_transaction_type,
		SUM(amount) AS total FROM branchrevenue 
GROUP BY revenue_transaction_type 
ORDER BY total DESC;

#Average Revenue FROM BRANCH
SELECT branch_name,
		AVG(amount) as Avgamount 
FROM branchrevenue 
GROUP BY branch_name 
ORDER by avgamount DESC;

#Branch Revenue Contribution
SELECT Branch_Name,
       ROUND(
           SUM(Amount)*100/
           (SELECT SUM(Amount) FROM branchrevenue)
       ,2) AS RevenueContribution
FROM branchrevenue
GROUP BY Branch_Name
ORDER BY RevenueContribution DESC;