/* =========================
   POLICY ANALYSIS
========================= */

#Total Policies
SELECT Count(PolicyID) AS Total_policies 
FROM policy ;

#Total Policy Type 
SELECT PolicyType,count(policyId) As Policies 
FROM policy 
GROUP BY policyType 
ORDER BY Policies DESC;

#TotalRevenue
SELECT SUM(PremiumAmount) AS TotalRevenue 
FROM policy;

#Average Premium amount per Policy
SELECT AVG(PremiumAmount) as AvgAmount 
FROM policy;

#Highest Premium paid Customer
SELECT * 
FROM policy 
ORDER BY PremiumAmount DESC LIMIT 1;

#Avg Premium by PolicyType
SELECT policytype,
		Avg(PremiumAmount) AS avgamount 
FROM POlicy 
GROUP BY policytype 
Order by Avgamount DESC;

#Total Revenue generated BY Policy  Type
SELECT PolicyType,
		SUM(premiumamount) AS TotalRevenue 
FROM policy 
GROUP BY policytype 
ORDER BY TotalRevenue DESC;

#Total status of the policies
SELECT * FROM policy;
SELECT policyStatus, 
		COUNT(*) AS Total 
FROM policy 
GROUP BY policystatus 
Order by total desc;

#Top 5 Customers by Premium
SELECT CustomerID,
       SUM(PremiumAmount) AS TotalPremium
FROM policy
GROUP BY CustomerID
ORDER BY TotalPremium DESC
LIMIT 5;
 
#Active vs lapsed vs Terminated %
SELECT PolicyStatus,
       COUNT(*) AS TotalPolicies,
       ROUND(COUNT(*)*100/(SELECT COUNT(*) FROM policy),2) AS Percentage
FROM policy
GROUP BY PolicyStatus;

#Gender wise policies
SELECT Gender,
		COUNT(*) AS totalpolicy 
FROM policy 
GROUP BY Gender 
ORDER BY totalpolicy DESC;

#Gender Wise Revenue
SELECT Gender,
		sum(PremiumAmount) as Total 
FROM policy 
GROUP BY Gender 
ORDER BY Total DESC;

#Age Bucket Wise Policies
SELECT
CASE
    WHEN Age < 20 THEN 'Below 20'
    WHEN Age BETWEEN 20 AND 40 THEN '20-40'
    WHEN Age BETWEEN 41 AND 60 THEN '41-60'
    ELSE 'Above 60'
END AS AgeBucket,
COUNT(*) AS TotalPolicies
FROM policy
GROUP BY AgeBucket
ORDER BY TotalPolicies DESC;
